# The main entry point of workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

include: "rules/common.smk"
include: "rules/qc.smk"

def all_input(wildcards):

    wanted_input = []

    wanted_input.extend(["results/qc/multiqc/multiqc.html"])

    return wanted_input

rule all:
    input: all_input
