# The main entry point of workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/cutadapt.smk"
include: "rules/mapping.smk"

def all_input(wildcards):

    wanted_input = []

    # QC with fastQC and multiQC
    wanted_input.extend(["results/qc/multiqc/multiqc.html"])

    # trimming reads
    for (sample, unit) in units.index:
        if is_single_end(sample, unit):
            wanted_input.extend(expand(
                    [
                        "results/trimmed/{sample}-{unit}.fastq.gz",
                        "results/trimmed/{sample}-{unit}.se.qc.txt"
                    ],
                    sample = sample,
                    unit = unit
                )
            )
        else:
            wanted_input.extend(
                expand (
                    [
                        "results/trimmed/{sample}-{unit}.1.fastq.gz",
                        "results/trimmed/{sample}-{unit}.2.fastq.gz",
                        "results/trimmed/{sample}-{unit}.pe.qc.txt"
                    ],
                    sample = sample,
                    unit = unit
            )
        )

    # mapping and merging bam-files
    wanted_input.extend(
        expand (
            [
                "results/mapped/{sample}-{unit}.bam",
                "results/mapped/dedup/{sample}-{unit}.bam",
                "results/mapped/dedup/{sample}-{unit}.metrics.txt",
                "results/mapped/merged_with_dups.bam",
                "results/mapped/merged.bam"
            ],
            sample = sample,
            unit = unit
        )
    )

    return wanted_input

rule all:
    input: all_input
