$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples:
    type: string
  units:
    type: string

# entries that have to be in the config file for successful validation
required:
  - samples
  - units
